name: Build & Release with PyInstaller
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
env:
  SCRIPT_NAME: script.py
  BASE_NAME: booklistbuilder
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        shell: bash
        run: |
          set -x
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build Windows EXE
        shell: bash
        run: |
          set -x
          pyinstaller --onefile --log-level DEBUG --name "${{ env.BASE_NAME }}-${{ github.ref_name }}-windows" --icon="booklistbuilder.ico" ${{ env.SCRIPT_NAME }}
      - name: Release & upload Windows EXE
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: dist/${{ env.BASE_NAME }}-${{ github.ref_name }}-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    needs: build-windows
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        shell: bash
        run: |
          set -x
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build mac Mach-O executable
        shell: bash
        run: |
          set -x
          pyinstaller --onefile --log-level DEBUG --name "${{ env.BASE_NAME }}-${{ github.ref_name }}-mac" ${{ env.SCRIPT_NAME }}
      - name: Release & upload mac Mach-O
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: dist/${{ env.BASE_NAME }}-${{ github.ref_name }}-mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}